[env:esp32doit-devkit-v1]
platform = espressif32
board = esp32doit-devkit-v1
framework = arduino
monitor_speed = 115200
lib_deps =
  adafruit/Adafruit GFX Library @ ^1.11.5
  adafruit/Adafruit SSD1306 @ ^2.5.7
  adafruit/DHT sensor library @ ^1.4.4
  adafruit/Adafruit Unified Sensor @ ^1.1.9
  madhephaestus/ESP32Servo @ ^0.13.0